package com.jay.parser.parser

class StrategyRegistry(
    private val strategies: List<LayoutStrategy>
) {
    fun choose(lines: List<String>): LayoutStrategy? {
        return strategies
            .filter { it.matches(lines) }
            .maxByOrNull { it.score(lines) }
    }

    companion object {
        fun default(): StrategyRegistry {
            return StrategyRegistry(
                listOf(
                    AdvanceProductsLayoutStrategy(),
                    AlaskaRestaurantLayoutStrategy(),
                    AlphaChemicalServicesLayoutStrategy(),
                    AldonGatewayLayoutStrategy(),
                    AllPointsIlLayoutStrategy(),
                    ApothecaryProductsLayoutStrategy(),
                    AtheaLaboratoriesLayoutStrategy(),
                    AquaPhoenixScientificLayoutStrategy(),
                    AquaResearchLayoutStrategy(),
                    AutoChlorSystemTnLayoutStrategy(),
                    BaileysTestStripsLayoutStrategy(),
                    BartovationLayoutStrategy(),
                    BetaProcesosLayoutStrategy(),
                    BlueDragonDefenseLayoutStrategy(),
                    BillAlemanLayoutStrategy(),
                    BunzlLayoutStrategy(),
                    ButlerChemicalLayoutStrategy(),
                    CambridgeEnvironmentalLayoutStrategy(),
                    CarolinaBiologicalLayoutStrategy(),
                    CharlotteProductsLayoutStrategy(),
                    ChemSupplyLayoutStrategy(),
                    ChosunMeasurementLayoutStrategy(),
                    CmRepresentacionesLayoutStrategy(),
                    CommunityLearningLayoutStrategy(),
                    CompanhiaNitroLayoutStrategy(),
                    ContecDistributionLayoutStrategy(),
                    CovenantAviationLayoutStrategy(),
                    CovidienCtLayoutStrategy(),
                    CulturesForHealthLayoutStrategy(),
                    CurisSystemLayoutStrategy(),
                    DaiggerLayoutStrategy(),
                    DiversifiedFoodserviceLayoutStrategy(),
                    DiverseyTaiwanLayoutStrategy(),
                    DiverseyTurkeyLayoutStrategy(),
                    DevereLayoutStrategy(),
                    DoveLayoutStrategy(),
                    DrakeLayoutStrategy(),
                    DsaDetectionLayoutStrategy(),
                    DwDaviesLayoutStrategy(),
                    EcaEducationalServicesLayoutStrategy(),
                    EasternCrownLayoutStrategy(),
                    EcolabLayoutStrategy(),
                    EcolabPeruLayoutStrategy(),
                    EiscoSciLayoutStrategy(),
                    ElectronicControlsDesignLayoutStrategy(),
                    EnvironicsLayoutStrategy(),
                    EtdDirectSupplyLayoutStrategy(),
                    ExplosiaLayoutStrategy(),
                    ExtractTechnologyLayoutStrategy(),
                    FisherScientificCoLayoutStrategy(),
                    FlinnScientificLayoutStrategy(),
                    FranzZielLayoutStrategy(),
                    FreseniusMedicalLayoutStrategy(),
                    GascoIndustrialLayoutStrategy(),
                    GeorgesIncLayoutStrategy(),
                    Hand2MindLayoutStrategy(),
                    HawaiiChemicalLayoutStrategy(),
                    HomeBrewOhioLayoutStrategy(),
                    HomeScienceToolsLayoutStrategy(),
                    IndustriasCorySasLayoutStrategy(),
                    InterconChemicalLayoutStrategy(),
                    IsssCoLtdLayoutStrategy(),
                    JayhawkSalesTxLayoutStrategy(),
                    JayhawkSalesWiLayoutStrategy(),
                    JonkmanEquipmentLayoutStrategy(),
                    KochFoodsMorristownLayoutStrategy(),
                    KrowneLayoutStrategy(),
                    LaboratorySalesLayoutStrategy(),
                    LitRefrigerationLayoutStrategy(),
                    MattChlorLayoutStrategy(),
                    MccoyHealthScienceLayoutStrategy(),
                    MedlineLayoutStrategy(),
                    MedivatorsLayoutStrategy(),
                    MedtronicSurgicalSolutionsLayoutStrategy(),
                    MirOilLayoutStrategy(),
                    MoreFlavorLayoutStrategy(),
                    NalcoCompanyLayoutStrategy(),
                    NascoWiLayoutStrategy(),
                    NationalChemicalsLayoutStrategy(),
                    NaturesWorkshopLayoutStrategy(),
                    OsceolaSupplyLayoutStrategy(),
                    OzmResearchLayoutStrategy(),
                    PdqManufacturingLayoutStrategy(),
                    PinetreeInstrumentsLayoutStrategy(),
                    PlantProductsLayoutStrategy(),
                    PrecisionEuropeLayoutStrategy(),
                    ProlabScientificLayoutStrategy(),
                    ProwestSuppliesLayoutStrategy(),
                    QualityScienceLabsLayoutStrategy(),
                    QvortexLayoutStrategy(),
                    RideauGroupLayoutStrategy(),
                    RilabLayoutStrategy(),
                    SaniTestLayoutStrategy(),
                    SaintLukesHealthLayoutStrategy(),
                    ScinoPharmTaiwanLayoutStrategy(),
                    SanitechLayoutStrategy(),
                    SchoolSpecialtyLayoutStrategy(),
                    ScienceFirstLayoutStrategy(),
                    SeaboardFarmsLayoutStrategy(),
                    SensonicsIntlLayoutStrategy(),
                    SomersetEducationalLayoutStrategy(),
                    StMarksPowderLayoutStrategy(),
                    StatlabLayoutStrategy(),
                    TaylorTechnologiesLayoutStrategy(),
                    TcdPartsLayoutStrategy(),
                    ThermalScientificLayoutStrategy(),
                    TransatlanticTradingLayoutStrategy(),
                    TsmSolutionsLayoutStrategy(),
                    TsaInvoiceLayoutStrategy(),
                    UniKemLayoutStrategy(),
                    UnitedScientificLayoutStrategy(),
                    UnipakLayoutStrategy(),
                    UsFoodsLayoutStrategy(),
                    UsaBlueBookLayoutStrategy(),
                    VikingPureLayoutStrategy(),
                    VwrLayoutStrategy(),
                    WebbChemicalAndPaperLayoutStrategy(),
                    WestlabLayoutStrategy(),
                    WilkemScientificLayoutStrategy(),
                    WilkensAndersonLayoutStrategy()

                )
            )
        }
    }
}
